### ISSUE TITLE
  AttributeError: 'DiskDevice' object has no attribute 'fd' introduced in #4129

### ISSUE THREAD

**Issue by Maroc-OS** [geohot/tinygrad#4139]
#4129 introduced an AttributeError when trying to close non existing file descriptor

```
tinygrad_latest/test/test_copy_speed.py::TestCopySpeed::testCopySHMtoDefault
  /usr/local/lib/python3.11/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function Buffer.__del__ at 0x108b44f40>
  
  Traceback (most recent call last):
    File "/Users/mac/Desktop/tinygrad/tinygrad_latest/tinygrad/buffer.py", line 43, in __del__
      self.allocator.free(self._buf, self.nbytes, self.options)
    File "/Users/mac/Desktop/tinygrad/tinygrad_latest/tinygrad/device.py", line 107, in free
      self._free(opaque, options if options is not None else BufferOptions())
    File "/Users/mac/Desktop/tinygrad/tinygrad_latest/tinygrad/runtime/ops_disk.py", line 23, in _free
      def _free(self, buf, options): self.device._might_close()
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/mac/Desktop/tinygrad/tinygrad_latest/tinygrad/runtime/ops_disk.py", line 85, in _might_close
      os.close(self.fd)
               ^^^^^^^
  AttributeError: 'DiskDevice' object has no attribute 'fd'
```
